# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/TOP/TOP.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP || ORIG_REF_NAME==TOP} -quiet] -quiet

# IP: bd/TOP/ip/TOP_CPU_0_0/TOP_CPU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_CPU_0_0 || ORIG_REF_NAME==TOP_CPU_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_mem_control_0_0/TOP_mem_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_mem_control_0_0 || ORIG_REF_NAME==TOP_mem_control_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_blk_mem_gen_1_0/TOP_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_blk_mem_gen_1_0 || ORIG_REF_NAME==TOP_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_bram_ctrl_0_0/TOP_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_axi_bram_ctrl_0_0 || ORIG_REF_NAME==TOP_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_processing_system7_0_0/TOP_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_processing_system7_0_0 || ORIG_REF_NAME==TOP_processing_system7_0_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_rst_ps7_0_50M_0 || ORIG_REF_NAME==TOP_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/TOP/ip/TOP_axi_smc_0/TOP_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_axi_smc_0 || ORIG_REF_NAME==TOP_axi_smc_0} -quiet] -quiet

# Block Designs: bd/TOP/ip/TOP_axi_smc_0/bd_0/bd_ab6f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_5/bd_ab6f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_11/bd_ab6f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_12/bd_ab6f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_6/bd_ab6f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_7/bd_ab6f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_8/bd_ab6f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_9/bd_ab6f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_10/bd_ab6f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_2/bd_ab6f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_3/bd_ab6f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_4/bd_ab6f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_0/bd_ab6f_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_1/bd_ab6f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/TOP/ip/TOP_blk_mem_gen_0_1/TOP_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TOP_blk_mem_gen_0_1 || ORIG_REF_NAME==TOP_blk_mem_gen_0_1} -quiet] -quiet

# XDC: bd/TOP/ip/TOP_blk_mem_gen_1_0/TOP_blk_mem_gen_1_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_bram_ctrl_0_0/TOP_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_processing_system7_0_0/TOP_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_processing_system7_0_0 || ORIG_REF_NAME==TOP_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_rst_ps7_0_50M_0 || ORIG_REF_NAME==TOP_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TOP_rst_ps7_0_50M_0 || ORIG_REF_NAME==TOP_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_5/bd_ab6f_s00a2s_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_11/bd_ab6f_m00s2a_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_6/bd_ab6f_sarn_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_7/bd_ab6f_srn_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_8/bd_ab6f_sawn_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_9/bd_ab6f_swn_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_10/bd_ab6f_sbn_0_ooc.xdc

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_1/bd_ab6f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_1/bd_ab6f_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/TOP/ip/TOP_axi_smc_0/ooc.xdc

# XDC: bd/TOP/ip/TOP_blk_mem_gen_0_1/TOP_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/TOP/TOP_ooc.xdc
