# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-73336-LVCS-Air14Plus/incrSyn
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.cache/wt [current_project]
set_property parent.project_path C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/a.coe
read_verilog -library xil_defaultlib {
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/DC.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/EXE.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MEM.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX16.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX2.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX8.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/PCC.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_FILE.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_HE.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_HE_PC.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/WB.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/_MUX16.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/_MUX8.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/pipe_control.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/CPU.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/mem_control.v
  C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/hdl/TOP_wrapper.v
}
add_files C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/TOP.bd
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_blk_mem_gen_1_0/TOP_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_bram_ctrl_0_0/TOP_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_processing_system7_0_0/TOP_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_rst_ps7_0_50M_0/TOP_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_5/bd_ab6f_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_11/bd_ab6f_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_6/bd_ab6f_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_7/bd_ab6f_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_8/bd_ab6f_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_9/bd_ab6f_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_10/bd_ab6f_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_1/bd_ab6f_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/bd_0/ip/ip_1/bd_ab6f_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_blk_mem_gen_0_1/TOP_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/TOP_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top TOP_wrapper -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TOP_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file TOP_wrapper_utilization_synth.rpt -pb TOP_wrapper_utilization_synth.pb"
