# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ipshared/02c8/hdl/verilog
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ipshared/e2dd/hdl/verilog
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_blk_mem_gen_0_1
  } {
      D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ipshared/02c8/hdl/verilog
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ipshared/e2dd/hdl/verilog
    c:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/ip/TOP_blk_mem_gen_0_1
  } {
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_CPU_0_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_mem_control_0_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_blk_mem_gen_1_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_axi_bram_ctrl_0_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_processing_system7_0_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_rst_ps7_0_50M_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_axi_smc_0_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/realtime/TOP_blk_mem_gen_0_1_stub.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/DC.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/EXE.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MEM.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX16.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX2.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/MUX8.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/PCC.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_FILE.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_HE.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/REG_HE_PC.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/WB.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/_MUX16.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/_MUX8.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/pipe_control.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/CPU.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/imports/new/mem_control.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/synth/TOP.v
      C:/Users/LVCS/Desktop/RISCVCPU/RISCVCPU.srcs/sources_1/bd/TOP/hdl/TOP_wrapper.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top TOP_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/LVCS/Desktop/RISCVCPU/.Xil/Vivado-31628-LVCS-Air14Plus/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
